---
- name: Converge
  hosts: all
  gather_facts: false
  become: true
  vars:
    netbird:
      skip_login: True
  roles:
    - role: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
  tasks:
    - name: Verify that Netbird is installed
      ansible.builtin.shell:
        cmd: netbird version
      changed_when: False